# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a3452f6bed2f022dcd4de73c3467500b3035fb4bb4c72d6c2d3b386c048dac1057f9a3dcc22c57575a8877d0aba395cf6a5bfbec244c73de09635bbdc0d984e

test:
  secret_key_base: 3f4762e15dbd93a0069bdc0042171d0d0854c19fe3e06a4813a78439a3158b3112d0d365d71584f3ee9bcfc3d315173430dbb534c7cc10091cc5b14f7f61b2fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
